apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-a-dev
  namespace: argocd
spec:
  project: helm-guestbook-a
  source:
    repoURL: https://github.com/dustinvanbuskirk/helm-guestbook.git
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      valueFiles:
      - ../applications/helm-guestbook-a/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev