apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  labels:
    app: {{ template "helm-guestbook.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  gateways:
  - {{ template "helm-guestbook.fullname" . }}
  hosts:
  - "{{ .Release.Name }}.{{ .Release.Namespace }}.sales-dev.codefresh.io"
  http:
  - name: primary        # referenced in canary.trafficRouting.istio.virtualService.routes
    route:
    - destination:
        host: stable-{{ template "helm-guestbook.fullname" . }} # referenced in canary.stableService
      weight: 100
    - destination:
        host: canary-{{ template "helm-guestbook.fullname" . }} # referenced in canary.canaryService
      weight: 0